server:
  port: 8080
  context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinkman?characterEncoding=UTF-8
    username: root
    password: Good1234

mybatis:
  typeAliasesPackage: com.ifunq.sfht.mapper
  mapper-locations: classpath:mybatis/mapper/*.xml

name: 杨华