server:
  port: 8081
  context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinkman?characterEncoding=UTF-8
    username: root
    password: rol11998888
http:
  encoding:
    charset: UTF-8
    force: true
    enabled: true

mybatis:
  typeAliasesPackage: com.ifunq.sfht.mapper
  mapper-locations: classpath:mybatis/mapper/*.xml

name: 杨华